services:
  db:
    image: teste
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: optimize
      POSTGRES_DB: optimize
      POSTGRES_USER: optimize
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M

    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432

volumes:
  pgdata:
