services:
  db:
    build:
      context: db
      dockerfile: Dockerfile    

    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: optimize
      POSTGRES_DB: optimize
    command: ["postgres", "-c", "log_statement=all"]

    ports:
      - 6968:5432
    
  adminer:
    image: adminer
    ports:
    - 8080:8080
    
volumes:
  pgdata: